### ISSUE TITLE
Bug: Excess Python.exe Instances

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#245]
![Screenshot 2021-01-14 221714](https://user-images.githubusercontent.com/15325110/104589907-49f8a280-56b6-11eb-9380-28dfd47f0388.png)
The Salt Minion appears to launch excess python.exe processes.
Approx 150-200 processes.
Salt log shows possible communication issues to the master although the master is contactable.

2021-01-14 17:53:10,845 [salt.utils.process:906 ][ERROR   ][10124] An un-handled exception from the multiprocessing process 'ProcessPayload' was caught:
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3001rc1_16_ge92daf88a2-py3.7.egg\salt\utils\process.py", line 897, in wrapped_run_func
    return run_func()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3001rc1_16_ge92daf88a2-py3.7.egg\salt\minion.py", line 1745, in _target
    minion_instance = cls(opts)
  File "c:\salt\bin\lib\site-packages\salt-3001rc1_16_ge92daf88a2-py3.7.egg\salt\minion.py", line 1224, in __init__
    self.io_loop = ZMQDefaultLoop.current()
  File "c:\salt\bin\lib\site-packages\salt-3001rc1_16_ge92daf88a2-py3.7.egg\salt\ext\tornado\ioloop.py", line 215, in current
    return IOLoop.instance()
  File "c:\salt\bin\lib\site-packages\salt-3001rc1_16_ge92daf88a2-py3.7.egg\salt\ext\tornado\ioloop.py", line 163, in instance
    IOLoop._instance = IOLoop()
  File "c:\salt\bin\lib\site-packages\salt-3001rc1_16_ge92daf88a2-py3.7.egg\salt\ext\tornado\util.py", line 294, in __new__
    instance.initialize(*args, **init_kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3001rc1_16_ge92daf88a2-py3.7.egg\salt\ext\tornado\platform\select.py", line 77, in initialize
    super(SelectIOLoop, self).initialize(impl=_Select(), **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3001rc1_16_ge92daf88a2-py3.7.egg\salt\ext\tornado\ioloop.py", line 711, in initialize
    self._waker = Waker()
  File "c:\salt\bin\lib\site-packages\salt-3001rc1_16_ge92daf88a2-py3.7.egg\salt\ext\tornado\platform\common.py", line 65, in __init__
    self.writer.connect(connect_address)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by wh1te909** [comment]
salt has been removed in develop, next release we will be salt free :)
