### ISSUE TITLE
ERRO TO CREATE USER RMM

### ISSUE THREAD

**Issue by dermscan-TN** [wh1te909/tacticalrmm#428]
Hi,

I have an error when the script tell me to create user on password request i have this:
> Username: admin
Traceback (most recent call last):
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InsufficientPrivilege: ERREUR:  droit refusé pour la table django_migrations

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/rmm/api/tacticalrmm/manage.py", line 21, in <module>
    main()
  File "/rmm/api/tacticalrmm/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/rmm/api/env/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/base.py", line 397, in execute
    self.check_migrations()
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/base.py", line 486, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 78, in applied_migrations
    return {(migration.app, migration.name): migration for migration in self.migration_qs}
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ERREUR:  droit refusé pour la table django_migrations
Traceback (most recent call last):
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InsufficientPrivilege: ERREUR:  droit refusé pour la table accounts_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/rmm/api/tacticalrmm/manage.py", line 21, in <module>
    main()
  File "/rmm/api/tacticalrmm/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/rmm/api/tacticalrmm/accounts/management/commands/generate_barcode.py", line 22, in handle
    user = User.objects.get(username=username)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/rmm/api/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ERREUR:  droit refusé pour la table  accounts_user

> 

I'm on VM debian 10

**Comment by wh1te909** [comment]
just tested on debian 10, not able to reproduce:
```
********************************************************************************
Please create your login for the RMM website and django admin
********************************************************************************
Username: admin
Password:
Password (again):
Superuser created successfully.
```

where is your vm running? on what cloud provider?
please paste the entire output of the install script so I can check it for errors

**Comment by dermscan-TN** [comment]
it's running in vmware esxi 6.7
look in attachment my full script log
[script rmm.txt](https://github.com/wh1te909/tacticalrmm/files/6367913/script.rmm.txt)

**Comment by wh1te909** [comment]
the install script needs to be run on a fresh instance, you can't run it twice or after a botched install attempt
wipe the VM and start over and then paste the entire output from the very beginning

**Comment by dermscan-TN** [comment]
yes i relaunch on frsh install is good. but i need previously install nginx
