### ISSUE TITLE
SyntaxError: EOL while scanning string literal - MESH_TOKEN_KEY = 'Resetting power events indexes...

### ISSUE THREAD

**Issue by WouterLS** [wh1te909/tacticalrmm#447]
**Server Info (please complete the following information):**
OS Ubuntu 

**Installation Method:**
Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
It seems the MESH_TOKEY_KEY isn't getting filled with the right data.

**To Reproduce**
https://github.com/wh1te909/tacticalrmm/tree/develop/docker

**Expected behavior**
should be able to log in into tacticalRMM after a clean docker install

**Screenshots**
SyntaxError: EOL while scanning string literal
cannot delete non-empty directory: tmp
cannot delete non-empty directory: certs
Traceback (most recent call last):
  File "/opt/tactical/api/manage.py", line 21, in <module>
    main()
  File "/opt/tactical/api/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/opt/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/tactical/api/tacticalrmm/__init__.py", line 3, in <module>
    from .celery import app as celery_app
  File "/opt/tactical/api/tacticalrmm/celery.py", line 13, in <module>
    backend="redis://" + settings.REDIS_HOST,
  File "/opt/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/tactical/api/tacticalrmm/settings.py", line 46, in <module>
    from .local_settings import *
  File "/opt/tactical/api/tacticalrmm/local_settings.py", line 54
    MESH_TOKEN_KEY = 'Resetting power events indexes...
                                                       ^
SyntaxError: EOL while scanning string literal

**Comment by sadnub** [comment]
Can you send the output of this command

```
sudo docker-compose exec tactical-backend cat /opt/tactical/tmp/mesh_token
```

That is where the mesh token is saved and is populated into the local_settings.py file

**Comment by sadnub** [comment]
Mesh might have also outputed some additional text when the -logintoken command was running. You can also delete that mesh_token file and it will regenerate a key.

```
sudo docker-compose exec tactical-backend rm -f /opt/tactical/tmp/mesh_token
sudo docker-compose restart
```

**Comment by WouterLS** [comment]
Yeah,
something like that. there were 2 lines in front saying "Resetting power events indexes...
and resetting something else"

I've manually edited the file to just contain the key and restarted the trmm-init container and after that it was fine.
