### ISSUE TITLE
Bad credentials / bad request

### ISSUE THREAD

**Issue by krystophe** [wh1te909/tacticalrmm#536]
Hi,

I'm running tacticalrmm on docker, I can access the webui but when I'm trying to connect with my first created account I've got an error 400 "bad credential" after submit the two factor token.

Details of the request:
400     POST   /login/

I'have a 200 with OPTIONS on /login/

Have you any idea to solve this problem ?

**Comment by wh1te909** [comment]
reset your 2fa token from cli https://wh1te909.github.io/tacticalrmm/faq/#how-do-i-reset-password-or-2-factor-token

**Comment by krystophe** [comment]
Hi,

Thanks for response, it's work now.
I'm on the /setup and for upload I need to upload the meshagent but it's seems that the command doesn't work:

python manage.py get_mesh_exe_url   on trmm-backend.
here is the output:
Traceback (most recent call last):
  File "/opt/tactical/api/manage.py", line 21, in <module>
    main()
  File "/opt/tactical/api/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/tactical/api/core/management/commands/get_mesh_exe_url.py", line 50, in handle
    asyncio.get_event_loop().run_until_complete(self.websocket_call(mesh_settings))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/tactical/api/core/management/commands/get_mesh_exe_url.py", line 41, in websocket_call
    async for message in websocket:
  File "/opt/venv/lib/python3.9/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/opt/venv/lib/python3.9/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/opt/venv/lib/python3.9/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

any idea ?

**Comment by sadnub** [comment]
Login to the tacticalrmm dashboard and go to Settings > Global Settings > Mesh central.

Are all of the settings populated in there?

**Comment by krystophe** [comment]
This is my first connection and I have the page /setup with the requierd meshagent to upload and I don't have this .exe and can't click on finish.

**Comment by silversword411** [comment]
Goto https;//mesh.example.com to get the mesh agents you need to give trmm

**Comment by krystophe** [comment]
Hi,

Thanks it's work. Now I can access to my dashboard tacticalrmm
