### ISSUE TITLE
find_software error

### ISSUE THREAD

**Issue by cmiscloni** [wh1te909/tacticalrmm#682]
Server Info
 - OS: Debian 10.9
 - RMM Version : 0.8.2

Installation Method:
  Standard

- Agent version 1.6.1
- Agent OS: W10

Describe the bug
Error when I try to get a list of agents with a specific software installed

To Reproduce

```
python manage.py find_software "beats"
Found Beats winlogbeat 7.8.0 (x86_64) installed on xx
Found Beats winlogbeat 7.8.0 (x86_64) installed on xxx
Found Beats winlogbeat 7.6.1 (x86_64) installed on xxx
Found Beats winlogbeat 7.7.1 (x86_64) installed on xxx
Found Beats winlogbeat 7.8.0 (x86_64) installed on xxx
Found Beats winlogbeat 7.8.0 (x86_64) installed on xxxx
Found Beats winlogbeat 7.8.0 (x86_64) installed on xxxx
Found Beats winlogbeat 7.8.0 (x86_64) installed on xxxx
Found Beats winlogbeat 7.8.0 (x86_64) installed on xxxx
Traceback (most recent call last):
  File "/rmm/api/tacticalrmm/manage.py", line 21, in <module>
    main()
  File "/rmm/api/tacticalrmm/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/rmm/api/env/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/rmm/api/tacticalrmm/software/management/commands/find_software.py", line 17, in handle
    sw = agent.installedsoftware_set.first().software
AttributeError: 'NoneType' object has no attribute 'software'
```

**Comment by wh1te909** [comment]
fixed, will be in next release (or you can manually edit the file and apply changes then re-run the management command, see https://github.com/wh1te909/tacticalrmm/commit/e44453877c66a428cbd174f0935fb2e7fc332e6b)

**Comment by wh1te909** [comment]
added in release 0.8.3
