### ISSUE TITLE
Bug:  Newly installed agent isn't reporting

### ISSUE THREAD

**Issue by rtwright68** [wh1te909/tacticalrmm#93]
The agent is green, but when I try to run salt test.ping against it:

MAB-FS1-61:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20200903095430762989
ERROR: Minions returned with non-zero exit code
tactical@ubuntu-rtw-tactical-rmm:~$ salt-run jobs.lookup_jid 20200903095430762989
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/master?
[WARNING ] Could not write out jid file for job 20200903095653274885. Retrying.
[WARNING ] Could not write out jid file for job 20200903095653274885. Retrying.
[WARNING ] Could not write out jid file for job 20200903095653274885. Retrying.
[WARNING ] Could not write out jid file for job 20200903095653274885. Retrying.
[WARNING ] Could not write out jid file for job 20200903095653274885. Retrying.
[ERROR   ] prep_jid could not store a jid after 5 tries.
[CRITICAL] The specified 'local_cache' returner threw a stack trace:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 123, in prep_jid
    with salt.utils.files.fopen(os.path.join(jid_dir, "jid"), "wb+") as fn_:
  File "/usr/lib/python3/dist-packages/salt/utils/files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/f0/28fd6b902e129207cea3115367772245620db61fb34b903ce7ebcdf9e7458d/jid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 123, in prep_jid
    with salt.utils.files.fopen(os.path.join(jid_dir, "jid"), "wb+") as fn_:
  File "/usr/lib/python3/dist-packages/salt/utils/files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/f0/28fd6b902e129207cea3115367772245620db61fb34b903ce7ebcdf9e7458d/jid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 123, in prep_jid
    with salt.utils.files.fopen(os.path.join(jid_dir, "jid"), "wb+") as fn_:
  File "/usr/lib/python3/dist-packages/salt/utils/files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/f0/28fd6b902e129207cea3115367772245620db61fb34b903ce7ebcdf9e7458d/jid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 123, in prep_jid
    with salt.utils.files.fopen(os.path.join(jid_dir, "jid"), "wb+") as fn_:
  File "/usr/lib/python3/dist-packages/salt/utils/files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/f0/28fd6b902e129207cea3115367772245620db61fb34b903ce7ebcdf9e7458d/jid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 123, in prep_jid
    with salt.utils.files.fopen(os.path.join(jid_dir, "jid"), "wb+") as fn_:
  File "/usr/lib/python3/dist-packages/salt/utils/files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/f0/28fd6b902e129207cea3115367772245620db61fb34b903ce7ebcdf9e7458d/jid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/job.py", line 75, in store_job
    mminion.returners[jidstore_fstr](False, passed_jid=load["jid"])
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 131, in prep_jid
    return prep_jid(
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 131, in prep_jid
    return prep_jid(
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 131, in prep_jid
    return prep_jid(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 104, in prep_jid
    raise salt.exceptions.SaltCacheError(err)
salt.exceptions.SaltCacheError: prep_jid could not store a jid after 5 tries.
[CRITICAL] The specified 'local_cache' returner threw a stack trace:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/job.py", line 142, in store_job
    mminion.returners[fstr](load)
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 155, in returner
    os.makedirs(hn_dir)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/cache/salt/master/jobs/f0/28fd6b902e129207cea3115367772245620db61fb34b903ce7ebcdf9e7458d'

**Comment by rtwright68** [comment]
Also ran against an agent that has been installed for some time and is reporting:

tactical@ubuntu-rtw-tactical-rmm:~$ sudo salt rtw-fs1-55 test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
tactical@ubuntu-rtw-tactical-rmm:~$ sudo salt RTW-FS1-55 test.ping
RTW-FS1-55:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20200903100609310541
ERROR: Minions returned with non-zero exit code

**Comment by wh1te909** [comment]
make sure to run ```salt-run jobs.lookup_jid``` with sudo or you'll get that permission denied error. Any salt command actually needs sudo.

So the tactical agent actually has nothing to do with the salt minion, 2 completely separate processes so seems like it's just a salt issue. First check to see if the ```salt-minion``` windows service is running. Then check the log file ```C:\salt\var\log\salt\minion``` and see if there are any errors.

**Comment by rtwright68** [comment]
Service was running enough to show the patches but not the hardware details.
Last couple of agents are now working ok.  I will close this ticket.
